# roles/firewall/tasks/main.yml
---
- name: Ensure firewalld is running
  ansible.builtin.systemd:
    name: firewalld
    state: started
    enabled: true

- name: Open web service ports
  ansible.posix.firewalld:
    service: "{{ item }}"
    permanent: true
    immediate: true
    state: enabled
  loop:
    - http
    - https
